X = {}
---@return table
X.build = function()
  local theme = {
    Normal = { fg = "#ce671c", bg = "#210e00" },
    FzfLuaBorder = { link = "Normal" },
    FzfLuaNormal = { link = "Normal" },
    NvimSpacing = { link = "Normal" },
    javaScript = { link = "Normal" },
    lessVariableValue = { link = "Normal" },
    ["@variable.parameter"] = { link = "Normal" },
    BlinkCmpDoc = { fg = "#e6803c", bg = "#404040" },
    BlinkCmpDocBorder = { fg = "#e6803c", bg = "#404040" },
    BlinkCmpDocSeparator = { fg = "#e6803c", bg = "#404040" },
    BlinkCmpKind = { fg = "#ffac51" },
    BlinkCmpKindText = { fg = "#ffac51", bg = "#404040" },
    BlinkCmpKindClass = { link = "BlinkCmpKindText" },
    BlinkCmpKindColor = { link = "BlinkCmpKindText" },
    BlinkCmpKindConstant = { link = "BlinkCmpKindText" },
    BlinkCmpKindConstructor = { link = "BlinkCmpKindText" },
    BlinkCmpKindEnum = { link = "BlinkCmpKindText" },
    BlinkCmpKindEnumMember = { link = "BlinkCmpKindText" },
    BlinkCmpKindEvent = { link = "BlinkCmpKindText" },
    BlinkCmpKindField = { link = "BlinkCmpKindText" },
    BlinkCmpKindFile = { link = "BlinkCmpKindText" },
    BlinkCmpKindFolder = { link = "BlinkCmpKindText" },
    BlinkCmpKindFunction = { link = "BlinkCmpKindText" },
    BlinkCmpKindInterface = { link = "BlinkCmpKindText" },
    BlinkCmpKindKeyword = { link = "BlinkCmpKindText" },
    BlinkCmpKindMethod = { link = "BlinkCmpKindText" },
    BlinkCmpKindModule = { link = "BlinkCmpKindText" },
    BlinkCmpKindOperator = { link = "BlinkCmpKindText" },
    BlinkCmpKindProperty = { link = "BlinkCmpKindText" },
    BlinkCmpKindReference = { link = "BlinkCmpKindText" },
    BlinkCmpKindSnippet = { link = "BlinkCmpKindText" },
    BlinkCmpKindStruct = { link = "BlinkCmpKindText" },
    BlinkCmpKindTypeParameter = { link = "BlinkCmpKindText" },
    BlinkCmpKindUnit = { link = "BlinkCmpKindText" },
    BlinkCmpKindValue = { link = "BlinkCmpKindText" },
    BlinkCmpKindVariable = { link = "BlinkCmpKindText" },
    BlinkCmpLabel = { fg = "#ffac51" },
    BlinkCmpLabelMatch = { fg = "#e6803c" },
    BlinkCmpMenu = { fg = "#ffac51", bg = "#404040" },
    BlinkCmpSignatureHelp = { fg = "#ffac51" },
    Boolean = { fg = "#f79b2e" },
    ["@boolean"] = { link = "Boolean" },
    ["@character"] = { link = "Character" },
    ["@string.escape"] = { link = "Character" },
    ["@string.special.path"] = { link = "Character" },
    CmpItemAbbrDeprecated = { fg = "#c43636" },
    CmpItemAbbrMatch = { fg = "#ffac51" },
    CmpItemAbbrMatchFuzzy = { link = "CmpItemAbbrMatch" },
    CmpItemKindFunction = { fg = "#f3cb00", bg = "#4a2911" },
    CmpItemKindMethod = { link = "CmpItemKindFunction" },
    CmpItemKindKeyword = { fg = "#f3cb00" },
    CmpItemKindProperty = { link = "CmpItemKindKeyword" },
    CmpItemKindUnit = { link = "CmpItemKindKeyword" },
    CmpItemKindText = { fg = "#ffac51", bg = "#4a2911" },
    CmpItemKindVariable = { fg = "#ffac51", bg = "#4a2911" },
    CmpItemKindInterface = { link = "CmpItemKindVariable" },
    ColorColumn = { bg = "#4a2911" },
    Comment = { fg = "#ffac51", bg = "#4a2911" },
    CtrlPLinePre = { link = "Comment" },
    LspCodeLens = { link = "Comment" },
    helpSectionDelim = { link = "Comment" },
    ["@comment"] = { link = "Comment" },
    ["@lsp.type.comment"] = { link = "Comment" },
    ["@string.docstrings"] = { link = "Comment" },
    ["@text.literal"] = { link = "Comment" },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.conditional.ternary"] = { link = "Conditional" },
    Constant = { fg = "#a53c00" },
    Character = { link = "Constant" },
    TelescopeResultsConstant = { link = "Constant" },
    TelescopeResultsStruct = { link = "Constant" },
    rubyConstant = { link = "Constant" },
    vimHiAttrib = { link = "Constant" },
    ["@attribute"] = { link = "Constant" },
    ["@constant"] = { link = "Constant" },
    ["@lsp.type.enumMember"] = { link = "Constant" },
    Cursor = { fg = "#ce671c", bg = "#000000" },
    FzfLuaCursor = { link = "Cursor" },
    CursorColumn = { bg = "#391d0a" },
    CursorLine = { bg = "#391d0a" },
    FzfLuaCursorLine = { link = "CursorLine" },
    CursorLineNr = { fg = "#ce671c", bg = "#391d0a", bold = true },
    FzfLuaCursorLineNr = { link = "CursorLineNr" },
    ["@keyword.debug"] = { link = "Debug" },
    ["@constant.macro"] = { link = "Define" },
    Delimiter = { fg = "#f39647" },
    NvimArrow = { link = "Delimiter" },
    NvimColon = { link = "Delimiter" },
    NvimComma = { link = "Delimiter" },
    NvimParenthesis = { link = "Delimiter" },
    Operator = { link = "Delimiter" },
    javaScriptBraces = { link = "Delimiter" },
    markdownLinkDelimiter = { link = "Delimiter" },
    markdownURLDelimiter = { link = "Delimiter" },
    vimContinue = { link = "Delimiter" },
    vimSetSep = { link = "Delimiter" },
    ["@punctuation"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { link = "Delimiter" },
    ["@punctuation.special"] = { link = "Delimiter" },
    DiagnosticDeprecated = { sp = "#c94848", strikethrough = true },
    DiagnosticHint = { fg = "#ffac51" },
    DiagnosticFloatingHint = { link = "DiagnosticHint" },
    DiagnosticHintFloating = { fg = "#fac473" },
    DiagnosticInfo = { fg = "#fac473" },
    DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
    DiagnosticOk = { fg = "#ffac51" },
    DiagnosticFloatingOk = { link = "DiagnosticOk" },
    DiagnosticSignOk = { link = "DiagnosticOk" },
    DiagnosticVirtualTextOk = { link = "DiagnosticOk" },
    DiagnosticSignError = { fg = "#c94848", bg = "#210e00" },
    DiagnosticSignHint = { fg = "#fac473", bg = "#210e00" },
    DiagnosticSignInfo = { fg = "#fac473", bg = "#210e00" },
    DiagnosticSignWarn = { fg = "#a89727", bg = "#210e00" },
    DiagnosticUnderlineError = { underline = true },
    DiagnosticUnderlineHint = { underline = true },
    DiagnosticUnderlineInfo = { underline = true },
    DiagnosticUnderlineOk = { underline = true },
    DiagnosticUnderlineWarn = { underline = true },
    DiagnosticUnnecessary = { fg = "#c43636", underline = true },
    DiagnosticVirtualTextError = { fg = "#c43636", bg = "#210e00" },
    DiagnosticVirtualTextHint = { fg = "#fac473", bg = "#210e00" },
    DiagnosticVirtualTextInfo = { fg = "#fac473", bg = "#210e00" },
    DiagnosticVirtualTextWarn = { fg = "#a89727", bg = "#210e00" },
    DiagnosticVirtualTextWarning = { fg = "#a89727" },
    DiagnosticWarn = { fg = "#a89727" },
    DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
    DiagnosticWarning = { fg = "#a89727" },
    DiagnosticFloatingWarning = { link = "DiagnosticWarning" },
    DiagnosticWarningFloating = { fg = "#a89727" },
    DiffAdd = { fg = "#404040", bg = "#210e00" },
    ["@diff.plus"] = { link = "DiffAdd" },
    ["@text.diff.add"] = { link = "DiffAdd" },
    DiffAdded = { fg = "#f3cb00", bg = "#404040" },
    DiffChange = { fg = "#404040", bg = "#a89727" },
    ["@diff.delta"] = { link = "DiffChange" },
    DiffDelete = { fg = "#c94848", bg = "#912929", bold = true },
    ["@diff.minus"] = { link = "DiffDelete" },
    ["@text.diff.delete"] = { link = "DiffDelete" },
    DiffRemoved = { fg = "#f39647", bg = "#404040" },
    DiffText = { fg = "#404040", bg = "#f39647", bold = true },
    Directory = { fg = "#f3cb00", bg = "#404040" },
    gitCommitFile = { link = "Directory" },
    ErrorMsg = { fg = "#c94848", bg = "#912929" },
    DiagnosticError = { link = "ErrorMsg" },
    DiagnosticErrorFloating = { link = "ErrorMsg" },
    DiagnosticFloatingError = { link = "ErrorMsg" },
    Error = { link = "ErrorMsg" },
    LazyReasonRuntime = { link = "ErrorMsg" },
    LazyTaskError = { link = "ErrorMsg" },
    NvimFigureBrace = { link = "ErrorMsg" },
    NvimInternalError = { link = "ErrorMsg" },
    NvimInvalid = { link = "ErrorMsg" },
    NvimInvalidSingleQuotedUnknownEscape = { link = "ErrorMsg" },
    NvimInvalidSpacing = { link = "ErrorMsg" },
    NvimSingleQuotedUnknownEscape = { link = "ErrorMsg" },
    ["@comment.error"] = { link = "ErrorMsg" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@number.float"] = { link = "Float" },
    FloatBorder = { fg = "#e6803c", bg = "#404040" },
    LspBorderBG = { link = "FloatBorder" },
    FloatShadow = { bg = "#000000" },
    FloatShadowThrough = { bg = "#281102" },
    FoldColumn = { fg = "#404040", bg = "#391d0a" },
    CursorLineFold = { link = "FoldColumn" },
    Folded = { fg = "#fac473", bg = "#000000" },
    Function = { fg = "#fad727" },
    TelescopeResultsFunction = { link = "Function" },
    ["@function"] = { link = "Function" },
    ["@function.call"] = { link = "Function" },
    ["@function.method"] = { link = "Function" },
    ["@function.method.call"] = { link = "Function" },
    ["@lsp.type.decorator"] = { link = "Function" },
    ["@lsp.type.function"] = { link = "Function" },
    ["@lsp.type.method"] = { link = "Function" },
    ["@method"] = { link = "Function" },
    GitSignsAdd = { fg = "#a89727", bg = "#4a2911" },
    GitSignsChange = { fg = "#f39647", bg = "#4a2911" },
    GitSignsDelete = { fg = "#c94848", bg = "#4a2911" },
    IblIndent = { fg = "#210e00", nocombine = true },
    IblScope = { fg = "#281102", nocombine = true },
    IblWhitespace = { fg = "#210e00", nocombine = true },
    Identifier = { fg = "#e6803c" },
    NvimIdentifier = { link = "Identifier" },
    TelescopeResultsIdentifier = { link = "Identifier" },
    rubyLocalVariableOrMethod = { link = "Identifier" },
    ["@attribute.builtin"] = { link = "Identifier" },
    ["@field"] = { link = "Identifier" },
    ["@lsp.type.parameter"] = { link = "Identifier" },
    ["@lsp.type.variable"] = { link = "Identifier" },
    ["@markup.math"] = { link = "Identifier" },
    ["@namespace"] = { link = "Identifier" },
    ["@parameter"] = { link = "Identifier" },
    ["@string.special.symbol"] = { link = "Identifier" },
    ["@tag.attribute"] = { link = "Identifier" },
    ["@text.reference"] = { link = "Identifier" },
    ["@variable"] = { link = "Identifier" },
    ["@variable.builtin"] = { link = "Identifier" },
    ["@variable.parameter.builtin"] = { link = "Identifier" },
    Ignore = { fg = "#404040", underline = true },
    Conceal = { link = "Ignore" },
    IncSearch = { fg = "#000000", bg = "#ffd500" },
    FzfLuaSearch = { link = "IncSearch" },
    ["@keyword.lua"] = { link = "Include" },
    ["@tag.delimiter"] = { link = "Include" },
    PreProc = { link = "Keyword" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.coroutine"] = { link = "Keyword" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.import"] = { link = "Keyword" },
    ["@keyword.modifier"] = { link = "Keyword" },
    ["@keyword.modifier.ruby"] = { link = "Keyword" },
    ["@keyword.operator"] = { link = "Keyword" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@keyword.type"] = { link = "Keyword" },
    ["@keyword.vim"] = { link = "Keyword" },
    ["@preproc"] = { link = "Keyword" },
    ["@label"] = { link = "Label" },
    LazyButton = { bg = "#210e00" },
    LazyButtonActive = { fg = "#000000", bg = "#fad727" },
    MasonHeaderSecondary = { link = "LazyButtonActive" },
    LazyComment = {},
    LazyCommit = {},
    LazyCommitIssue = { bg = "#210e00" },
    LazyCommitScope = { bg = "#210e00" },
    LazyCommitType = { bg = "#210e00" },
    LazyDimmed = {},
    LazyDir = {},
    LazyH1 = { fg = "#fad727", bg = "#210e00" },
    MasonHighlightBlockBold = { link = "LazyH1" },
    LazyH2 = { fg = "#fad727", bg = "#210e00" },
    MasonHighlightBlock = { link = "LazyH2" },
    LazyLocal = {},
    LazyNoCond = {},
    LazyNormal = { bg = "#210e00" },
    MasonNormal = { link = "LazyNormal" },
    LazyProgressDone = {},
    LazyProgressTodo = {},
    LazyProp = { bg = "#210e00" },
    LazyReasonCmd = {},
    LazyReasonEvent = {},
    LazyReasonFt = { bg = "#210e00" },
    LazyReasonImport = {},
    LazyReasonKeys = {},
    LazyReasonPlugin = {},
    LazyReasonSource = {},
    LazyReasonStart = {},
    LazyTaskOutput = { bg = "#210e00" },
    LazyUrl = { bg = "#000000" },
    LazyValue = {},
    LineNr = { fg = "#ffac51", bg = "#210e00" },
    LineNrAbove = { link = "LineNr" },
    LineNrBelow = { link = "LineNr" },
    TelescopeResultsLineNr = { link = "LineNr" },
    LspFloatWinNormal = { fg = "#ffd500", bg = "#3d3705" },
    LspReferenceRead = { fg = "#e6803c", sp = "#ffac51", bold = true, undercurl = true },
    LspReferenceText = { fg = "#ffd500", bg = "#391d0a", sp = "#ffac51", bold = true, undercurl = true },
    LspReferenceWrite = { fg = "#e6803c", sp = "#ffac51", bold = true, undercurl = true },
    LspSignatureActiveParameter = { sp = "#ffac51", bold = true, italic = true, underline = true },
    BlinkCmpSignatureHelpActiveParameter = { link = "LspSignatureActiveParameter" },
    ["@function.macro"] = { link = "Macro" },
    MasonError = {},
    MasonHeader = { fg = "#e6803c", bg = "#210e00" },
    MasonHeading = {},
    MasonHighlight = { fg = "#fad727", bg = "#391d0a" },
    MasonMutedBlockBold = { link = "MasonHighlight" },
    MasonHighlightBlockBoldSecondary = {},
    MasonHighlightBlockSecondary = {},
    MasonHighlightSecondary = {},
    MasonMuted = { fg = "#fad727", bg = "#391d0a" },
    MasonMutedBlock = { link = "MasonMuted" },
    MasonWarning = {},
    MatchParen = { fg = "#de6932", bold = true, underline = true },
    ModeMsg = { bold = true },
    MoreMsg = { fg = "#fad727", bold = true },
    NERDTreeHelp = { fg = "#ffd500", bg = "#391d0a" },
    NonText = { fg = "#404040", bg = "none", bold = true },
    BlinkCmpGhostText = { link = "NonText" },
    BlinkCmpLabelDeprecated = { link = "NonText" },
    EndOfBuffer = { link = "NonText" },
    Whitespace = { link = "NonText" },
    markdownCodeDelimiter = { link = "NonText" },
    markdownHeadingRule = { link = "NonText" },
    BlinkCmpSignatureHelpBorder = { link = "NormalFloat" },
    Number = { fg = "#e6803c" },
    Float = { link = "Number" },
    NvimNumber = { link = "Number" },
    rubyInstanceVariable = { link = "Number" },
    ["@number"] = { link = "Number" },
    TelescopeResultsOperator = { link = "Operator" },
    ["@operator"] = { link = "Operator" },
    Pmenu = { fg = "#ffac51", bg = "#404040" },
    BlinkCmpMenuBorder = { link = "Pmenu" },
    NormalFloat = { link = "Pmenu" },
    PmenuExtra = { link = "Pmenu" },
    BlinkCmpLabelDescription = { link = "PmenuExtra" },
    BlinkCmpLabelDetail = { link = "PmenuExtra" },
    BlinkCmpSource = { link = "PmenuExtra" },
    PmenuKind = { fg = "#ce671c" },
    PmenuSbar = { bg = "#404040" },
    BlinkCmpScrollBarGutter = { link = "PmenuSbar" },
    FzfLuaScrollFloatEmpty = { link = "PmenuSbar" },
    PmenuSel = { fg = "#ce671c", bg = "#ffac51" },
    BlinkCmpMenuSelection = { link = "PmenuSel" },
    PmenuExtraSel = { link = "PmenuSel" },
    PmenuKindSel = { link = "PmenuSel" },
    PmenuThumb = { fg = "#ffac51", bg = "#ce671c" },
    BlinkCmpScrollBarThumb = { link = "PmenuThumb" },
    FzfLuaScrollFloatFull = { link = "PmenuThumb" },
    Define = { link = "PreProc" },
    Include = { link = "PreProc" },
    Macro = { link = "PreProc" },
    PreCondit = { link = "PreProc" },
    Question = { fg = "#fad727", bold = true },
    RedrawDebugClear = { fg = "#404040", bg = "#ffac51" },
    RedrawDebugComposed = { fg = "#404040", bg = "#fad727" },
    RedrawDebugNormal = { reverse = true },
    RedrawDebugRecompose = { fg = "#404040", bg = "#a89727" },
    ["@keyword.repeat"] = { link = "Repeat" },
    Search = { fg = "#404040", bg = "#ffd500" },
    CurSearch = { link = "Search" },
    QuickFixLine = { link = "Search" },
    Substitute = { link = "Search" },
    SignColumn = { fg = "#404040", bg = "#391d0a" },
    CursorLineSign = { link = "SignColumn" },
    Special = { fg = "#ffd500" },
    Debug = { link = "Special" },
    LazySpecial = { link = "Special" },
    SpecialChar = { link = "Special" },
    SpecialComment = { link = "Special" },
    Tag = { link = "Special" },
    TelescopeMatching = { link = "Special" },
    TelescopePreviewMatch = { link = "Special" },
    TelescopeResultsClass = { link = "Special" },
    TelescopeResultsFileIcon = { link = "Special" },
    ["@constant.builtin"] = { link = "Special" },
    ["@constructor"] = { link = "Special" },
    ["@string.regexp"] = { link = "Special" },
    ["@string.special"] = { link = "Special" },
    ["@character.special"] = { link = "SpecialChar" },
    SpecialKey = { fg = "#e6803c" },
    SpellBad = { fg = "#f79b2e", bg = "#c94848", bold = true, underline = true },
    SpellCap = { fg = "#ffd500", bg = "#000000", underline = true },
    SpellLocal = { fg = "#a89727", bg = "#000000", underline = true },
    SpellRare = { fg = "#f39647", bg = "#000000", underline = true },
    Statement = { fg = "#ffd500", bold = true },
    Conditional = { link = "Statement" },
    Exception = { link = "Statement" },
    Keyword = { link = "Statement" },
    Label = { link = "Statement" },
    Repeat = { link = "Statement" },
    helpHyperTextEntry = { link = "Statement" },
    phpDefine = { link = "Statement" },
    rubyDefine = { link = "Statement" },
    ["@markup.checked"] = { link = "Statement" },
    ["@markup.list"] = { link = "Statement" },
    ["@markup.unchecked"] = { link = "Statement" },
    StatusLine = { fg = "#ffac51", bg = "#281102", bold = true },
    MsgSeparator = { link = "StatusLine" },
    StatusLineNC = { fg = "#404040", bg = "#281102", bold = true },
    String = { fg = "#fac473" },
    CtrlPMatch = { link = "String" },
    NERDTreeExecFile = { link = "String" },
    NvimString = { link = "String" },
    TelescopePreviewDirectory = { link = "String" },
    helpExample = { link = "String" },
    markdownCodeBlock = { link = "String" },
    phpHereDoc = { link = "String" },
    ["@markup.quote"] = { link = "String" },
    ["@string"] = { link = "String" },
    SyntasticErrorSign = { fg = "#fac473" },
    SyntasticWarningSign = { fg = "#a89727" },
    TabLine = { fg = "#404040", bg = "#000000" },
    TabLineFill = { fg = "#ffd500", bg = "#210e00" },
    TabLineSel = { fg = "#210e00", bg = "#fad727", bold = true },
    TabLineSelSep = { fg = "#fad727", bg = "#210e00", bold = true },
    TabLineSep = { fg = "#391d0a", bg = "#210e00" },
    ["@tag"] = { link = "Tag" },
    ["@tag.builtin"] = { link = "Tag" },
    TelescopeBorder = { fg = "#ffd500", bg = "#404040" },
    TelescopePreviewBorder = { link = "TelescopeBorder" },
    TelescopePromptCounter = { link = "TelescopeBorder" },
    TelescopeResultsBorder = { link = "TelescopeBorder" },
    TelescopeMultiIcon = {},
    TelescopeMultiSelection = {},
    TelescopeNormal = { bg = "#210e00" },
    TelescopePreviewBlock = {},
    TelescopePreviewCharDev = {},
    TelescopePreviewDate = {},
    TelescopePreviewExecute = {},
    TelescopePreviewGroup = {},
    TelescopePreviewHyphen = {},
    TelescopePreviewLink = {},
    TelescopePreviewMessage = { fg = "#ffd500", bold = true },
    TelescopePreviewMessageFillchar = {},
    TelescopePreviewNormal = { bg = "#210e00" },
    TelescopePreviewPipe = {},
    TelescopePreviewRead = {},
    TelescopePreviewSize = {},
    TelescopePreviewSocket = {},
    TelescopePreviewSticky = {},
    TelescopePreviewUser = {},
    TelescopePreviewWrite = {},
    TelescopePromptBorder = { fg = "#ffd500", bg = "#404040" },
    TelescopePromptNormal = { bg = "#210e00" },
    TelescopeResultsComment = {},
    TelescopeResultsDiffUntracked = {},
    TelescopeResultsField = {},
    TelescopeResultsNormal = { bg = "#210e00" },
    TelescopeResultsNumber = {},
    TelescopeResultsSpecialComment = {},
    TelescopeSelection = { bg = "#39274D" },
    TelescopePreviewLine = { link = "TelescopeSelection" },
    TelescopeSelectionCaret = { fg = "#ffd500", bg = "#281102", bold = true },
    TelescopeTitle = { fg = "#ffd500", bg = "#281102" },
    TelescopePreviewTitle = { link = "TelescopeTitle" },
    TelescopePromptPrefix = { link = "TelescopeTitle" },
    TelescopePromptTitle = { link = "TelescopeTitle" },
    TelescopeResultsTitle = { link = "TelescopeTitle" },
    TermCursor = { reverse = true },
    Title = { fg = "#ffd500", bold = true },
    FloatTitle = { link = "Title" },
    helpHeadline = { link = "Title" },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.heading.1"] = { link = "Title" },
    ["@markup.heading.2"] = { link = "Title" },
    ["@markup.heading.3"] = { link = "Title" },
    ["@markup.heading.4"] = { link = "Title" },
    ["@markup.heading.5"] = { link = "Title" },
    ["@markup.heading.6"] = { link = "Title" },
    ["@text.title"] = { link = "Title" },
    Todo = { fg = "#ffac51", bold = true, underline = true },
    ["@comment.todo"] = { link = "Todo" },
    ["@text.todo"] = { link = "Todo" },
    TroubleFsBasename = { fg = "#fac473", bg = "none" },
    TroubleFsCount = { fg = "#fac473", bg = "none" },
    TroubleFsFilename = { fg = "#fac473", bg = "none" },
    TroubleFsSource = { fg = "#fac473", bg = "none" },
    TroubleIconArray = { bg = "none" },
    TroubleIconBoolean = { bg = "none" },
    TroubleIconClass = { bg = "none" },
    TroubleIconConstant = { bg = "none" },
    TroubleIconConstructor = { bg = "none" },
    TroubleIconFunction = { bg = "none" },
    TroubleIconNamespace = { bg = "none" },
    TroubleIconNull = { bg = "none" },
    TroubleIconNumber = { bg = "none" },
    TroubleIconObject = { bg = "none" },
    TroubleIconOperator = { fg = "#e6803c", bg = "none" },
    TroubleIndentFoldClosed = { fg = "#e6803c", bg = "none" },
    TroubleIndentFoldOpen = { fg = "#e6803c", bg = "none" },
    TroubleIndentLast = { fg = "#e6803c", bg = "none" },
    TroubleIndentMiddle = { fg = "#e6803c", bg = "none" },
    TroubleIndentTop = { fg = "#e6803c", bg = "none" },
    TroubleIndentWs = { fg = "#fac473", bg = "none" },
    TroubleNormal = { fg = "#fac473", bg = "none" },
    TroubleNormalNC = { fg = "#fac473", bg = "none" },
    TroublePos = { fg = "#fac473", bg = "none" },
    TroublePreview = { fg = "#fac473", bg = "none" },
    Type = { fg = "#f79b2e", bold = true },
    NvimNumberPrefix = { link = "Type" },
    NvimOptionSigil = { link = "Type" },
    StorageClass = { link = "Type" },
    Structure = { link = "Type" },
    Typedef = { link = "Type" },
    ["@function.builtin"] = { link = "Type" },
    ["@lsp.type.type"] = { link = "Type" },
    ["@type"] = { link = "Type" },
    ["@module"] = { link = "Typedef" },
    ["@module.builtin"] = { link = "Typedef" },
    ["@type.builtin"] = { link = "Typedef" },
    ["@type.definition"] = { link = "Typedef" },
    Underlined = { fg = "#fad727", underline = true },
    helpHyperTextJump = { link = "Underlined" },
    helpURL = { link = "Underlined" },
    htmlLink = { link = "Underlined" },
    ["@markup.link"] = { link = "Underlined" },
    ["@markup.link.label"] = { link = "Underlined" },
    ["@markup.link.url"] = { link = "Underlined" },
    ["@string.special.url"] = { link = "Underlined" },
    ["@text.underline"] = { link = "Underlined" },
    ["@text.uri"] = { link = "Underlined" },
    User1 = { fg = "#ffd500", bg = "#281102" },
    User2 = { fg = "#e6803c", bg = "#281102" },
    User3 = { fg = "#c94848", bg = "#281102" },
    User4 = { fg = "#a89727", bg = "#281102" },
    User5 = { fg = "#ffac51", bg = "#281102" },
    User6 = { fg = "#fad727", bg = "#281102" },
    User7 = { fg = "#64a050", bg = "#281102" },
    User8 = { fg = "#f39647", bg = "#281102" },
    User9 = { fg = "#a53c00", bg = "#281102" },
    VertSplit = { fg = "#a53c00", bg = "#210e00" },
    WinSeparator = { link = "VertSplit" },
    Visual = { fg = "#ffac51", bg = "#404040" },
    BlinkCmpDocCursorLine = { link = "Visual" },
    WarningMsg = { fg = "#a89727" },
    ["@comment.warning"] = { link = "WarningMsg" },
    WhichKey = { fg = "#ffac51", bg = "none" },
    WhichKeyBorder = { bg = "#404040" },
    WhichKeyDesc = { fg = "#f79b2e", bg = "none" },
    WhichKeyFloat = { bg = "#404040" },
    WhichKeyGroup = { fg = "#f79b2e", bg = "#404040" },
    WhichKeySeparator = { fg = "#ffd500", bg = "none" },
    WhichKeyValue = { fg = "#fad727", bg = "none" },
    WildMenu = { fg = "#000000", bg = "#404040" },
    WinBar = { bold = true },
    WinBarNC = { link = "WinBar" },
    gitCommitBranch = { fg = "#fad727" },
    gitCommitSelectedFile = { fg = "#ffd500" },
    gitCommitSelectedType = { fg = "#ffd500" },
    gitCommitUnmergedFile = { fg = "#f79b2e" },
    gitCommitDiscardedFile = { link = "gitCommitUnmergedFile" },
    gitCommitUntrackedFile = { link = "gitCommitUnmergedFile" },
    gitCommitUnmergedType = { fg = "#f79b2e" },
    gitCommitDiscardedType = { link = "gitCommitUnmergedType" },
    htmlArg = { fg = "#ffd500" },
    htmlBold = { bold = true },
    htmlBoldItalic = { bold = true, underline = true },
    htmlBoldUnderline = { bold = true, underline = true },
    htmlBoldUnderlineItalic = { bold = true, underline = true },
    htmlH1 = { bold = true },
    htmlItalic = { underline = true },
    htmlTag = { fg = "#f79b2e" },
    htmlEndTag = { link = "htmlTag" },
    htmlTagName = { fg = "#f79b2e" },
    htmlUnderline = { underline = true },
    htmlUnderlineItalic = { underline = true },
    lCursor = { reverse = true },
    lessVariable = { fg = "#ffac51" },
    markdownBold = { bold = true },
    markdownItalic = { underline = true },
    mustacheMarker = { fg = "#e6803c" },
    mustachePartial = { fg = "#e6803c" },
    mustacheSection = { bold = true },
    mustacheVariable = { fg = "#ffac51" },
    mustacheVariableUnescape = { fg = "#e6803c" },
    netrwClassify = { fg = "#404040", bold = true },
    netrwExe = { fg = "#e6803c" },
    phpIdentifier = { fg = "#ffac51" },
    phpVarSelector = { link = "phpIdentifier" },
    phpSpecialFunction = { fg = "#fad727" },
    shDerefSimple = { fg = "#ffac51" },
    shDerefVar = { link = "shDerefSimple" },
    xmlTag = { fg = "#f79b2e" },
    xmlAttrib = { link = "xmlTag" },
    xmlEndTag = { link = "xmlTag" },
    xmlEqual = { link = "xmlTag" },
    xmlTagName = { fg = "#fad727" },
    xmlString = { link = "xmlTagName" },
    ["@comment.documentation"] = { fg = "#404040" },
    ["@comment.note"] = { fg = "#ffac51", bold = true },
    ["@lsp.type.property"] = { fg = "#a53c00" },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.underline"] = { underline = true },
    TelescopeResultsMethod = { link = "@method" },
    ["@property"] = { fg = "#a53c00" },
    TelescopeResultsVariable = { link = "@property" },
    ["@variable.member"] = { fg = "#a53c00" },
  }
  local opts = require("maginix").opts
  if opts.transparent then
    theme["Normal"].bg = "none"
    theme["StatusLine"].bg = "none"
  end
  if opts.overrides ~= false then
    theme = vim.tbl_deep_extend("force", theme, opts.overrides)
  end
  return theme
end
return X
